name: growlexicon
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  drift: ^2.34.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.4.2
  path: ^1.9.1
  path_provider: ^2.1.6
  shared_preferences: ^2.5.5
  sqflite: ^2.4.3
  sqflite_common_ffi: ^2.4.2+1
  sqlite3_flutter_libs: ^0.6.0+eol

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.34.0
  build_runner: ^2.15.1

flutter:
  uses-material-design: true
